apiVersion: v1
kind: Service
metadata:
  name: registry
  labels: 
    app: i40-aas
    service: registry
spec:
  ports:
  - targetPort: 4400
    port: 80
    protocol: TCP
    name: http
  selector:
    app: i40-aas
    service: registry
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
  labels: 
    app: i40-aas
    service: registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: i40-aas
      service: registry
  template: 
    metadata:
      labels:
        app: i40-aas
        service: registry
    spec:
      containers:
      - name: registry
        image: i40aas.azurecr.io/i40-aas-registry@SHA-PLACEHOLDER
        ports: 
        - containerPort: 4400
        envFrom:
        - secretRef:
            name: postgres-secret
        - configMapRef:
            name: registry-postgres
