---
apiVersion: v1
kind: ConfigMap
metadata:
  name: endpoint-registry
  labels: 
    app: i40-aas
    service: endpoint-registry
data:
  # Networking
  ENDPOINT_REGISTRY_PROTOCOL: http
  ENDPOINT_REGISTRY_HOST: endpoint-registry
  ENDPOINT_REGISTRY_PORT: "80"
  # Exposed Routes 
  ENDPOINT_REGISTRY_URL_SUFFIX: /endpoints
---
apiVersion: v1
kind: Secret
metadata:
  name: endpoint-registry
  labels: 
    app: i40-aas
    service: endpoint-registry
type: Opaque
stringData:
  ENDPOINT_REGISTRY_ADMIN_USER: admin
  ENDPOINT_REGISTRY_ADMIN_PASSWORD: admin
---
apiVersion: v1
kind: Service
metadata:
  name: endpoint-registry
  labels: 
    app: i40-aas
    service: endpoint-registry
spec:
  type: LoadBalancer
  ports:
  - targetPort: endpoint
    port: 80
    protocol: TCP
  selector:
    app: i40-aas
    service: endpoint-registry
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: endpoint-registry
  labels: 
    app: i40-aas
    service: endpoint-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: i40-aas
      service: endpoint-registry
  template: 
    metadata:
      labels:
        app: i40-aas
        service: endpoint-registry
    spec:
      containers:
      - name: registry
        image: sapi40/i40-aas-endpoint-registry
        ports: 
        - name: endpoint
          containerPort: 4400
        resources:
          limits:
            cpu: 50m
            memory: 500M
          requests:
            cpu: 25m
            memory: 263M
        envFrom:
        - secretRef:
            name: endpoint-registry-postgres
        - secretRef:
            name: endpoint-registry
        - configMapRef:
            name: endpoint-registry-postgres
---
