apiVersion: v1
kind: ConfigMap
metadata:
  name: service-addresses
data:
  REGISTRY_URL: endpoint-registry
  DATA_MANAGER_URL: http://data-manager
  ADAPTER_REG_URL: http://adapter-registry-exposed:80/adapters
