---
apiVersion: v1
kind: ConfigMap
metadata:
  name: endpoint-registry-postgres
data:
  POSTGRES_HOST: postgres-0.postgres-svc
  POSTGRES_PORT: "5432"
---
apiVersion: v1
kind: Secret
metadata:
  name: endpoint-registry-postgres
type: Opaque
stringData:
  POSTGRES_DB: AAS_REGISTRY
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
---
apiVersion: v1
kind: Secret
metadata:
  name: endpoint-registry-pgadmin
type: Opaque
stringData:
  PGADMIN_DEFAULT_EMAIL: admin
  PGADMIN_DEFAULT_PASSWORD: admin
---
kind: Service
apiVersion: v1
metadata:
  name: postgres-svc
spec:
  clusterIP: None
  selector:
    app: postgresql
  ports:
  - protocol: TCP
    port: 5432
    targetPort: database
---
kind: Service
apiVersion: v1
metadata:
  name: pgadmin-svc
spec:
  type: LoadBalancer
  selector:
    app: postgresql
  ports:
  - protocol: TCP
    port: 80
    targetPort: ui
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      app: postgresql
  serviceName: postgres-svc
  replicas: 1
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
        - name: postgres
          image: postgres:alpine
          imagePullPolicy: "IfNotPresent"
          ports:
            - name: database
              containerPort: 5432
          envFrom:
            - secretRef:
                name: endpoint-registry-postgres
        - name: pgadmin
          image: dpage/pgadmin4
          imagePullPolicy: "IfNotPresent"
          ports:
            - name: ui
              containerPort: 80
          envFrom:
            - secretRef:
                name: endpoint-registry-pgadmin
---
