---
apiVersion: v1
kind: ConfigMap
metadata:
  name: endpoint-registry-postgres
  labels:
    app: i40-aas
    service: endpoint-registry-postgres
data:
  # Networking
  ENDPOINT_REGISTRY_POSTGRES_HOST: postgres-0.postgres-svc
  ENDPOINT_REGISTRY_POSTGRES_PORT: "5432"
---
apiVersion: v1
kind: Secret
metadata:
  name: endpoint-registry-postgres
  labels:
    app: i40-aas
    service: endpoint-registry-postgres
type: Opaque
stringData:
  # Authentication  
  ENDPOINT_REGISTRY_POSTGRES_DB: AAS_REGISTRY
  ENDPOINT_REGISTRY_POSTGRES_USER: postgres
  ENDPOINT_REGISTRY_POSTGRES_PASSWORD: postgres
---
apiVersion: v1
kind: Secret
metadata:
  name: endpoint-registry-pgadmin
  labels:
    app: i40-aas
    service: endpoint-registry-postgres
type: Opaque
stringData:
  ENDPOINT_REGISTRY_DEFAULT_EMAIL: admin
  ENDPOINT_REGISTRY_DEFAULT_PASSWORD: admin
---
kind: Service
apiVersion: v1
metadata:
  name: postgres-svc
  labels:
    app: i40-aas
    service: endpoint-registry-postgres
spec:
  clusterIP: None
  selector:
    app: i40-aas
    service: endpoint-registry-postgres
  ports:
  - protocol: TCP
    port: 5432
    targetPort: database
---
kind: Service
apiVersion: v1
metadata:
  name: pgadmin-svc
  labels:
    app: i40-aas
    service: endpoint-registry-postgres
spec:
  type: LoadBalancer
  selector:
    app: i40-aas
    service: endpoint-registry-postgres
  ports:
  - protocol: TCP
    port: 80
    targetPort: ui
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  labels:
    app: i40-aas
    service: endpoint-registry-postgres
spec:
  selector:
    matchLabels:
      app: i40-aas
      service: endpoint-registry-postgres
  serviceName: postgres-svc
  replicas: 1
  template:
    metadata:
      labels:
        app: i40-aas
        service: endpoint-registry-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:alpine
          imagePullPolicy: "IfNotPresent"
          ports:
            - name: database
              containerPort: 5432
          envFrom:
            - secretRef:
                name: endpoint-registry-postgres
          volumeMounts:
            - mountPath: /var/lib/postgresql
              name: endpoint-registry-postgres
        - name: pgadmin
          image: dpage/pgadmin4
          imagePullPolicy: "IfNotPresent"
          ports:
            - name: ui
              containerPort: 80
          envFrom:
            - secretRef:
                name: endpoint-registry-pgadmin
  volumeClaimTemplates:
  - metadata:
      name: endpoint-registry-postgres
      labels:
        app: i40-aas
        service: endpoint-registry-postgres
    spec:
      storageClassName: default
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 100Mi
---
