
CREATE TABLE public.endpoints
(
    "endpointId" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "URL" character varying(1024) COLLATE pg_catalog."default" NOT NULL,
    protocol_name character varying(1024) COLLATE pg_catalog."default" NOT NULL,
    protocol_version character varying(1024) COLLATE pg_catalog."default",
    "aasId" character varying(1024) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT endpoints_pkey PRIMARY KEY ("endpointId"),
    CONSTRAINT "aasId" FOREIGN KEY ("aasId")
        REFERENCES public.asset_administration_shells ("aasId") MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    CONSTRAINT "endpointId" FOREIGN KEY ("endpointId")
        REFERENCES public.endpoints ("endpointId") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE public.endpoints
    OWNER to postgres;
