---
kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-mongodb
  labels:
    service: mongodb
    {{- include "i40-aas.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
  - protocol: TCP
    port: {{ .Values.skills.onboarding.database.port }}
    targetPort: database
  selector:
    service: mongodb
    {{- include "i40-aas.selectorLabels" . | nindent 4 }}
#---
#kind: Service
#apiVersion: v1
#metadata:
#  name: {{ .Release.Name }}-mongodb-api
#  labels:
#    service: mongodb
#    {{- include "i40-aas.labels" . | nindent 4 }}
#spec:
#  ports:
#  - protocol: TCP
#    port: 80
#    targetPort: database
#  selector:
#    service: mongodb
#    {{- include "i40-aas.selectorLabels" . | nindent 4 }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-mongodb
  labels:
    service: mongodb
    {{- include "i40-aas.labels" . | nindent 4 }}
spec:
  serviceName: {{ .Release.Name }}-mongodb
  replicas: 1
  selector:
    matchLabels:
      service: mongodb
      {{- include "i40-aas.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        service: mongodb
        {{- include "i40-aas.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: mongodb
          image: mongo
          imagePullPolicy: "IfNotPresent"
          ports:
            - name: database
              containerPort: {{ .Values.skills.onboarding.database.port }}
          env:
            - name: MONGO_INITDB_DATABASE
              value: {{ .Values.skills.onboarding.database.name | quote }}
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-skills-onboarding-database
                  key: SKILLS_ONBOARDING_DATABASE_USER
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-skills-onboarding-database
                  key: SKILLS_ONBOARDING_DATABASE_PASSWORD
          volumeMounts:
            - mountPath: /data/db
              name: {{ .Release.Name }}-mongodb
  volumeClaimTemplates:
    - metadata:
        name: {{ .Release.Name }}-mongodb
        labels:
          service: mongodb
          {{- include "i40-aas.labels" . | nindent 10 }}
      spec:
        storageClassName: {{ .Values.storageClassName }}
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 100Mi
---
