// Code generated by protoc-gen-go. DO NOT EDIT.
// source: interaction.proto

package interaction

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type InteractionStatusCode int32

const (
	InteractionStatusCode_Unknown InteractionStatusCode = 0
	InteractionStatusCode_Ok      InteractionStatusCode = 1
	InteractionStatusCode_Failed  InteractionStatusCode = 2
)

var InteractionStatusCode_name = map[int32]string{
	0: "Unknown",
	1: "Ok",
	2: "Failed",
}

var InteractionStatusCode_value = map[string]int32{
	"Unknown": 0,
	"Ok":      1,
	"Failed":  2,
}

func (x InteractionStatusCode) String() string {
	return proto.EnumName(InteractionStatusCode_name, int32(x))
}

func (InteractionStatusCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_43fb9bc5eb13a2f0, []int{0}
}

type InteractionStatus struct {
	Code                 InteractionStatusCode `protobuf:"varint,1,opt,name=Code,proto3,enum=interaction.InteractionStatusCode" json:"Code,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *InteractionStatus) Reset()         { *m = InteractionStatus{} }
func (m *InteractionStatus) String() string { return proto.CompactTextString(m) }
func (*InteractionStatus) ProtoMessage()    {}
func (*InteractionStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_43fb9bc5eb13a2f0, []int{0}
}

func (m *InteractionStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InteractionStatus.Unmarshal(m, b)
}
func (m *InteractionStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InteractionStatus.Marshal(b, m, deterministic)
}
func (m *InteractionStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InteractionStatus.Merge(m, src)
}
func (m *InteractionStatus) XXX_Size() int {
	return xxx_messageInfo_InteractionStatus.Size(m)
}
func (m *InteractionStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_InteractionStatus.DiscardUnknown(m)
}

var xxx_messageInfo_InteractionStatus proto.InternalMessageInfo

func (m *InteractionStatus) GetCode() InteractionStatusCode {
	if m != nil {
		return m.Code
	}
	return InteractionStatusCode_Unknown
}

type InteractionMessage struct {
	Frame                *Frame   `protobuf:"bytes,1,opt,name=frame,proto3" json:"frame,omitempty"`
	InteractionElements  []byte   `protobuf:"bytes,2,opt,name=interactionElements,proto3" json:"interactionElements,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InteractionMessage) Reset()         { *m = InteractionMessage{} }
func (m *InteractionMessage) String() string { return proto.CompactTextString(m) }
func (*InteractionMessage) ProtoMessage()    {}
func (*InteractionMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_43fb9bc5eb13a2f0, []int{1}
}

func (m *InteractionMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InteractionMessage.Unmarshal(m, b)
}
func (m *InteractionMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InteractionMessage.Marshal(b, m, deterministic)
}
func (m *InteractionMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InteractionMessage.Merge(m, src)
}
func (m *InteractionMessage) XXX_Size() int {
	return xxx_messageInfo_InteractionMessage.Size(m)
}
func (m *InteractionMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_InteractionMessage.DiscardUnknown(m)
}

var xxx_messageInfo_InteractionMessage proto.InternalMessageInfo

func (m *InteractionMessage) GetFrame() *Frame {
	if m != nil {
		return m.Frame
	}
	return nil
}

func (m *InteractionMessage) GetInteractionElements() []byte {
	if m != nil {
		return m.InteractionElements
	}
	return nil
}

type Frame struct {
	SemanticProtocol     string              `protobuf:"bytes,1,opt,name=semanticProtocol,proto3" json:"semanticProtocol,omitempty"`
	Type                 string              `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	MessageId            string              `protobuf:"bytes,3,opt,name=messageId,proto3" json:"messageId,omitempty"`
	ReplyBy              uint32              `protobuf:"varint,4,opt,name=replyBy,proto3" json:"replyBy,omitempty"`
	Receiver             *ConversationMember `protobuf:"bytes,5,opt,name=receiver,proto3" json:"receiver,omitempty"`
	Sender               *ConversationMember `protobuf:"bytes,6,opt,name=sender,proto3" json:"sender,omitempty"`
	ConversationId       string              `protobuf:"bytes,7,opt,name=conversationId,proto3" json:"conversationId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Frame) Reset()         { *m = Frame{} }
func (m *Frame) String() string { return proto.CompactTextString(m) }
func (*Frame) ProtoMessage()    {}
func (*Frame) Descriptor() ([]byte, []int) {
	return fileDescriptor_43fb9bc5eb13a2f0, []int{2}
}

func (m *Frame) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Frame.Unmarshal(m, b)
}
func (m *Frame) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Frame.Marshal(b, m, deterministic)
}
func (m *Frame) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Frame.Merge(m, src)
}
func (m *Frame) XXX_Size() int {
	return xxx_messageInfo_Frame.Size(m)
}
func (m *Frame) XXX_DiscardUnknown() {
	xxx_messageInfo_Frame.DiscardUnknown(m)
}

var xxx_messageInfo_Frame proto.InternalMessageInfo

func (m *Frame) GetSemanticProtocol() string {
	if m != nil {
		return m.SemanticProtocol
	}
	return ""
}

func (m *Frame) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Frame) GetMessageId() string {
	if m != nil {
		return m.MessageId
	}
	return ""
}

func (m *Frame) GetReplyBy() uint32 {
	if m != nil {
		return m.ReplyBy
	}
	return 0
}

func (m *Frame) GetReceiver() *ConversationMember {
	if m != nil {
		return m.Receiver
	}
	return nil
}

func (m *Frame) GetSender() *ConversationMember {
	if m != nil {
		return m.Sender
	}
	return nil
}

func (m *Frame) GetConversationId() string {
	if m != nil {
		return m.ConversationId
	}
	return ""
}

type ConversationMember struct {
	Identification       *Identification `protobuf:"bytes,1,opt,name=identification,proto3" json:"identification,omitempty"`
	Role                 *Role           `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ConversationMember) Reset()         { *m = ConversationMember{} }
func (m *ConversationMember) String() string { return proto.CompactTextString(m) }
func (*ConversationMember) ProtoMessage()    {}
func (*ConversationMember) Descriptor() ([]byte, []int) {
	return fileDescriptor_43fb9bc5eb13a2f0, []int{3}
}

func (m *ConversationMember) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConversationMember.Unmarshal(m, b)
}
func (m *ConversationMember) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConversationMember.Marshal(b, m, deterministic)
}
func (m *ConversationMember) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConversationMember.Merge(m, src)
}
func (m *ConversationMember) XXX_Size() int {
	return xxx_messageInfo_ConversationMember.Size(m)
}
func (m *ConversationMember) XXX_DiscardUnknown() {
	xxx_messageInfo_ConversationMember.DiscardUnknown(m)
}

var xxx_messageInfo_ConversationMember proto.InternalMessageInfo

func (m *ConversationMember) GetIdentification() *Identification {
	if m != nil {
		return m.Identification
	}
	return nil
}

func (m *ConversationMember) GetRole() *Role {
	if m != nil {
		return m.Role
	}
	return nil
}

type Role struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Role) Reset()         { *m = Role{} }
func (m *Role) String() string { return proto.CompactTextString(m) }
func (*Role) ProtoMessage()    {}
func (*Role) Descriptor() ([]byte, []int) {
	return fileDescriptor_43fb9bc5eb13a2f0, []int{4}
}

func (m *Role) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Role.Unmarshal(m, b)
}
func (m *Role) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Role.Marshal(b, m, deterministic)
}
func (m *Role) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Role.Merge(m, src)
}
func (m *Role) XXX_Size() int {
	return xxx_messageInfo_Role.Size(m)
}
func (m *Role) XXX_DiscardUnknown() {
	xxx_messageInfo_Role.DiscardUnknown(m)
}

var xxx_messageInfo_Role proto.InternalMessageInfo

func (m *Role) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Identification struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	IdType               string   `protobuf:"bytes,2,opt,name=idType,proto3" json:"idType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Identification) Reset()         { *m = Identification{} }
func (m *Identification) String() string { return proto.CompactTextString(m) }
func (*Identification) ProtoMessage()    {}
func (*Identification) Descriptor() ([]byte, []int) {
	return fileDescriptor_43fb9bc5eb13a2f0, []int{5}
}

func (m *Identification) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Identification.Unmarshal(m, b)
}
func (m *Identification) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Identification.Marshal(b, m, deterministic)
}
func (m *Identification) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Identification.Merge(m, src)
}
func (m *Identification) XXX_Size() int {
	return xxx_messageInfo_Identification.Size(m)
}
func (m *Identification) XXX_DiscardUnknown() {
	xxx_messageInfo_Identification.DiscardUnknown(m)
}

var xxx_messageInfo_Identification proto.InternalMessageInfo

func (m *Identification) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Identification) GetIdType() string {
	if m != nil {
		return m.IdType
	}
	return ""
}

type InteractionElement struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InteractionElement) Reset()         { *m = InteractionElement{} }
func (m *InteractionElement) String() string { return proto.CompactTextString(m) }
func (*InteractionElement) ProtoMessage()    {}
func (*InteractionElement) Descriptor() ([]byte, []int) {
	return fileDescriptor_43fb9bc5eb13a2f0, []int{6}
}

func (m *InteractionElement) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InteractionElement.Unmarshal(m, b)
}
func (m *InteractionElement) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InteractionElement.Marshal(b, m, deterministic)
}
func (m *InteractionElement) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InteractionElement.Merge(m, src)
}
func (m *InteractionElement) XXX_Size() int {
	return xxx_messageInfo_InteractionElement.Size(m)
}
func (m *InteractionElement) XXX_DiscardUnknown() {
	xxx_messageInfo_InteractionElement.DiscardUnknown(m)
}

var xxx_messageInfo_InteractionElement proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("interaction.InteractionStatusCode", InteractionStatusCode_name, InteractionStatusCode_value)
	proto.RegisterType((*InteractionStatus)(nil), "interaction.InteractionStatus")
	proto.RegisterType((*InteractionMessage)(nil), "interaction.InteractionMessage")
	proto.RegisterType((*Frame)(nil), "interaction.Frame")
	proto.RegisterType((*ConversationMember)(nil), "interaction.ConversationMember")
	proto.RegisterType((*Role)(nil), "interaction.Role")
	proto.RegisterType((*Identification)(nil), "interaction.Identification")
	proto.RegisterType((*InteractionElement)(nil), "interaction.InteractionElement")
}

func init() { proto.RegisterFile("interaction.proto", fileDescriptor_43fb9bc5eb13a2f0) }

var fileDescriptor_43fb9bc5eb13a2f0 = []byte{
	// 443 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0xdf, 0x8b, 0xd3, 0x40,
	0x10, 0xbe, 0xc4, 0x34, 0xb5, 0x53, 0x0d, 0xed, 0xf8, 0x83, 0xe5, 0x14, 0xaf, 0x2c, 0x28, 0xe5,
	0x1e, 0x0e, 0xa9, 0xa0, 0x07, 0xbe, 0x59, 0x3c, 0x28, 0x22, 0xca, 0x9e, 0xf7, 0xe8, 0x43, 0x2e,
	0x3b, 0x27, 0xcb, 0x25, 0xbb, 0x61, 0xb3, 0x56, 0xfa, 0xe6, 0x3f, 0xe2, 0xff, 0x2a, 0xd9, 0xe4,
	0x6c, 0x72, 0xad, 0xe2, 0xdb, 0xce, 0x7c, 0xdf, 0x7c, 0xbb, 0x3b, 0xf3, 0x0d, 0x4c, 0x95, 0x76,
	0x64, 0xd3, 0xcc, 0x29, 0xa3, 0x4f, 0x4a, 0x6b, 0x9c, 0xc1, 0x71, 0x27, 0xc5, 0x3f, 0xc0, 0x74,
	0xb5, 0x0d, 0xcf, 0x5d, 0xea, 0xbe, 0x57, 0xf8, 0x1a, 0xa2, 0xa5, 0x91, 0xc4, 0x82, 0x59, 0x30,
	0x4f, 0x16, 0xfc, 0xa4, 0xab, 0xb1, 0xc3, 0xae, 0x99, 0xc2, 0xf3, 0x79, 0x09, 0xd8, 0x81, 0x3f,
	0x52, 0x55, 0xa5, 0xdf, 0x08, 0xe7, 0x30, 0xb8, 0xb2, 0x69, 0xd1, 0xc8, 0x8d, 0x17, 0xd8, 0x93,
	0x3b, 0xab, 0x11, 0xd1, 0x10, 0xf0, 0x25, 0x3c, 0xe8, 0x60, 0xef, 0x73, 0x2a, 0x48, 0xbb, 0x8a,
	0x85, 0xb3, 0x60, 0x7e, 0x4f, 0xec, 0x83, 0xf8, 0xaf, 0x10, 0x06, 0x5e, 0x02, 0x8f, 0x61, 0x52,
	0x51, 0x91, 0x6a, 0xa7, 0xb2, 0xcf, 0xf5, 0x37, 0x33, 0x93, 0xfb, 0x0b, 0x47, 0x62, 0x27, 0x8f,
	0x08, 0x91, 0xdb, 0x94, 0xe4, 0x85, 0x47, 0xc2, 0x9f, 0xf1, 0x29, 0x8c, 0x8a, 0xe6, 0xc1, 0x2b,
	0xc9, 0xee, 0x78, 0x60, 0x9b, 0x40, 0x06, 0x43, 0x4b, 0x65, 0xbe, 0x79, 0xb7, 0x61, 0xd1, 0x2c,
	0x98, 0xdf, 0x17, 0x37, 0x21, 0xbe, 0x85, 0xbb, 0x96, 0x32, 0x52, 0x6b, 0xb2, 0x6c, 0xe0, 0x3f,
	0x78, 0xd4, 0xfb, 0xe0, 0xd2, 0xe8, 0x35, 0xd9, 0x2a, 0x6d, 0x3a, 0x52, 0x5c, 0x92, 0x15, 0x7f,
	0x0a, 0xf0, 0x0d, 0xc4, 0x15, 0x69, 0x49, 0x96, 0xc5, 0xff, 0x57, 0xda, 0xd2, 0xf1, 0x05, 0x24,
	0x59, 0x07, 0x5d, 0x49, 0x36, 0xf4, 0x4f, 0xbe, 0x95, 0xe5, 0x3f, 0x03, 0xc0, 0x5d, 0x19, 0x5c,
	0x42, 0xa2, 0x24, 0x69, 0xa7, 0xae, 0x54, 0xe6, 0xf3, 0xed, 0x6c, 0x9e, 0xf4, 0x47, 0xdd, 0xa3,
	0x88, 0x5b, 0x25, 0xf8, 0x1c, 0x22, 0x6b, 0xf2, 0xa6, 0x8b, 0xe3, 0xc5, 0xb4, 0x57, 0x2a, 0x4c,
	0x4e, 0xc2, 0xc3, 0xfc, 0x10, 0xa2, 0x3a, 0xaa, 0x9b, 0xae, 0x6f, 0x5c, 0x30, 0x12, 0xfe, 0xcc,
	0x4f, 0x21, 0xe9, 0x5f, 0x82, 0x09, 0x84, 0x4a, 0xb6, 0x9c, 0x50, 0x49, 0x7c, 0x0c, 0xb1, 0x92,
	0x5f, 0xb6, 0xc3, 0x6a, 0x23, 0xfe, 0xb0, 0x67, 0xb5, 0xd6, 0x0f, 0xc7, 0xa7, 0xf0, 0x68, 0xaf,
	0x3f, 0x71, 0x0c, 0xc3, 0x0b, 0x7d, 0xad, 0xcd, 0x0f, 0x3d, 0x39, 0xc0, 0x18, 0xc2, 0x4f, 0xd7,
	0x93, 0x00, 0x01, 0xe2, 0xb3, 0x54, 0xe5, 0x24, 0x27, 0xe1, 0xa2, 0xea, 0xe9, 0x9d, 0x93, 0x5d,
	0xab, 0x8c, 0xf0, 0x2b, 0xb0, 0x8b, 0x32, 0x37, 0xa9, 0xdc, 0x63, 0xeb, 0xa3, 0xbf, 0xad, 0x45,
	0x4b, 0x38, 0x7c, 0xf6, 0xef, 0xbd, 0xe1, 0x07, 0x97, 0xb1, 0x5f, 0xc8, 0x57, 0xbf, 0x03, 0x00,
	0x00, 0xff, 0xff, 0xc2, 0x57, 0x41, 0x6d, 0xa5, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// InteractionServiceClient is the client API for InteractionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type InteractionServiceClient interface {
	UploadInteractionMessage(ctx context.Context, in *InteractionMessage, opts ...grpc.CallOption) (*InteractionStatus, error)
}

type interactionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInteractionServiceClient(cc grpc.ClientConnInterface) InteractionServiceClient {
	return &interactionServiceClient{cc}
}

func (c *interactionServiceClient) UploadInteractionMessage(ctx context.Context, in *InteractionMessage, opts ...grpc.CallOption) (*InteractionStatus, error) {
	out := new(InteractionStatus)
	err := c.cc.Invoke(ctx, "/interaction.InteractionService/UploadInteractionMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InteractionServiceServer is the server API for InteractionService service.
type InteractionServiceServer interface {
	UploadInteractionMessage(context.Context, *InteractionMessage) (*InteractionStatus, error)
}

// UnimplementedInteractionServiceServer can be embedded to have forward compatible implementations.
type UnimplementedInteractionServiceServer struct {
}

func (*UnimplementedInteractionServiceServer) UploadInteractionMessage(ctx context.Context, req *InteractionMessage) (*InteractionStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadInteractionMessage not implemented")
}

func RegisterInteractionServiceServer(s *grpc.Server, srv InteractionServiceServer) {
	s.RegisterService(&_InteractionService_serviceDesc, srv)
}

func _InteractionService_UploadInteractionMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InteractionMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InteractionServiceServer).UploadInteractionMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/interaction.InteractionService/UploadInteractionMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InteractionServiceServer).UploadInteractionMessage(ctx, req.(*InteractionMessage))
	}
	return interceptor(ctx, in, info, handler)
}

var _InteractionService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "interaction.InteractionService",
	HandlerType: (*InteractionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UploadInteractionMessage",
			Handler:    _InteractionService_UploadInteractionMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "interaction.proto",
}
