// Code generated by protoc-gen-go. DO NOT EDIT.
// source: interaction.proto

package interaction

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type InteractionStatusCode int32

const (
	InteractionStatusCode_UNKNOWN InteractionStatusCode = 0
	InteractionStatusCode_OK      InteractionStatusCode = 200
	InteractionStatusCode_FAILED  InteractionStatusCode = 500
)

var InteractionStatusCode_name = map[int32]string{
	0:   "UNKNOWN",
	200: "OK",
	500: "FAILED",
}

var InteractionStatusCode_value = map[string]int32{
	"UNKNOWN": 0,
	"OK":      200,
	"FAILED":  500,
}

func (x InteractionStatusCode) String() string {
	return proto.EnumName(InteractionStatusCode_name, int32(x))
}

func (InteractionStatusCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_43fb9bc5eb13a2f0, []int{0}
}

type InteractionStatus struct {
	Code                 InteractionStatusCode `protobuf:"varint,1,opt,name=code,proto3,enum=interaction.InteractionStatusCode" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *InteractionStatus) Reset()         { *m = InteractionStatus{} }
func (m *InteractionStatus) String() string { return proto.CompactTextString(m) }
func (*InteractionStatus) ProtoMessage()    {}
func (*InteractionStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_43fb9bc5eb13a2f0, []int{0}
}

func (m *InteractionStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InteractionStatus.Unmarshal(m, b)
}
func (m *InteractionStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InteractionStatus.Marshal(b, m, deterministic)
}
func (m *InteractionStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InteractionStatus.Merge(m, src)
}
func (m *InteractionStatus) XXX_Size() int {
	return xxx_messageInfo_InteractionStatus.Size(m)
}
func (m *InteractionStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_InteractionStatus.DiscardUnknown(m)
}

var xxx_messageInfo_InteractionStatus proto.InternalMessageInfo

func (m *InteractionStatus) GetCode() InteractionStatusCode {
	if m != nil {
		return m.Code
	}
	return InteractionStatusCode_UNKNOWN
}

type InteractionMessage struct {
	Frame                *Frame   `protobuf:"bytes,1,opt,name=frame,proto3" json:"frame,omitempty"`
	InteractionElements  []byte   `protobuf:"bytes,2,opt,name=interactionElements,proto3" json:"interactionElements,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InteractionMessage) Reset()         { *m = InteractionMessage{} }
func (m *InteractionMessage) String() string { return proto.CompactTextString(m) }
func (*InteractionMessage) ProtoMessage()    {}
func (*InteractionMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_43fb9bc5eb13a2f0, []int{1}
}

func (m *InteractionMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InteractionMessage.Unmarshal(m, b)
}
func (m *InteractionMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InteractionMessage.Marshal(b, m, deterministic)
}
func (m *InteractionMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InteractionMessage.Merge(m, src)
}
func (m *InteractionMessage) XXX_Size() int {
	return xxx_messageInfo_InteractionMessage.Size(m)
}
func (m *InteractionMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_InteractionMessage.DiscardUnknown(m)
}

var xxx_messageInfo_InteractionMessage proto.InternalMessageInfo

func (m *InteractionMessage) GetFrame() *Frame {
	if m != nil {
		return m.Frame
	}
	return nil
}

func (m *InteractionMessage) GetInteractionElements() []byte {
	if m != nil {
		return m.InteractionElements
	}
	return nil
}

type Frame struct {
	SemanticProtocol     string              `protobuf:"bytes,1,opt,name=semanticProtocol,proto3" json:"semanticProtocol,omitempty"`
	Type                 string              `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	MessageId            string              `protobuf:"bytes,3,opt,name=messageId,proto3" json:"messageId,omitempty"`
	ReplyBy              uint32              `protobuf:"varint,4,opt,name=replyBy,proto3" json:"replyBy,omitempty"`
	Receiver             *ConversationMember `protobuf:"bytes,5,opt,name=receiver,proto3" json:"receiver,omitempty"`
	Sender               *ConversationMember `protobuf:"bytes,6,opt,name=sender,proto3" json:"sender,omitempty"`
	ConversationId       string              `protobuf:"bytes,7,opt,name=conversationId,proto3" json:"conversationId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Frame) Reset()         { *m = Frame{} }
func (m *Frame) String() string { return proto.CompactTextString(m) }
func (*Frame) ProtoMessage()    {}
func (*Frame) Descriptor() ([]byte, []int) {
	return fileDescriptor_43fb9bc5eb13a2f0, []int{2}
}

func (m *Frame) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Frame.Unmarshal(m, b)
}
func (m *Frame) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Frame.Marshal(b, m, deterministic)
}
func (m *Frame) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Frame.Merge(m, src)
}
func (m *Frame) XXX_Size() int {
	return xxx_messageInfo_Frame.Size(m)
}
func (m *Frame) XXX_DiscardUnknown() {
	xxx_messageInfo_Frame.DiscardUnknown(m)
}

var xxx_messageInfo_Frame proto.InternalMessageInfo

func (m *Frame) GetSemanticProtocol() string {
	if m != nil {
		return m.SemanticProtocol
	}
	return ""
}

func (m *Frame) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Frame) GetMessageId() string {
	if m != nil {
		return m.MessageId
	}
	return ""
}

func (m *Frame) GetReplyBy() uint32 {
	if m != nil {
		return m.ReplyBy
	}
	return 0
}

func (m *Frame) GetReceiver() *ConversationMember {
	if m != nil {
		return m.Receiver
	}
	return nil
}

func (m *Frame) GetSender() *ConversationMember {
	if m != nil {
		return m.Sender
	}
	return nil
}

func (m *Frame) GetConversationId() string {
	if m != nil {
		return m.ConversationId
	}
	return ""
}

type ConversationMember struct {
	Identification       *Identification `protobuf:"bytes,1,opt,name=identification,proto3" json:"identification,omitempty"`
	Role                 *Role           `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ConversationMember) Reset()         { *m = ConversationMember{} }
func (m *ConversationMember) String() string { return proto.CompactTextString(m) }
func (*ConversationMember) ProtoMessage()    {}
func (*ConversationMember) Descriptor() ([]byte, []int) {
	return fileDescriptor_43fb9bc5eb13a2f0, []int{3}
}

func (m *ConversationMember) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConversationMember.Unmarshal(m, b)
}
func (m *ConversationMember) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConversationMember.Marshal(b, m, deterministic)
}
func (m *ConversationMember) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConversationMember.Merge(m, src)
}
func (m *ConversationMember) XXX_Size() int {
	return xxx_messageInfo_ConversationMember.Size(m)
}
func (m *ConversationMember) XXX_DiscardUnknown() {
	xxx_messageInfo_ConversationMember.DiscardUnknown(m)
}

var xxx_messageInfo_ConversationMember proto.InternalMessageInfo

func (m *ConversationMember) GetIdentification() *Identification {
	if m != nil {
		return m.Identification
	}
	return nil
}

func (m *ConversationMember) GetRole() *Role {
	if m != nil {
		return m.Role
	}
	return nil
}

type Role struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Role) Reset()         { *m = Role{} }
func (m *Role) String() string { return proto.CompactTextString(m) }
func (*Role) ProtoMessage()    {}
func (*Role) Descriptor() ([]byte, []int) {
	return fileDescriptor_43fb9bc5eb13a2f0, []int{4}
}

func (m *Role) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Role.Unmarshal(m, b)
}
func (m *Role) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Role.Marshal(b, m, deterministic)
}
func (m *Role) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Role.Merge(m, src)
}
func (m *Role) XXX_Size() int {
	return xxx_messageInfo_Role.Size(m)
}
func (m *Role) XXX_DiscardUnknown() {
	xxx_messageInfo_Role.DiscardUnknown(m)
}

var xxx_messageInfo_Role proto.InternalMessageInfo

func (m *Role) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Identification struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	IdType               string   `protobuf:"bytes,2,opt,name=idType,proto3" json:"idType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Identification) Reset()         { *m = Identification{} }
func (m *Identification) String() string { return proto.CompactTextString(m) }
func (*Identification) ProtoMessage()    {}
func (*Identification) Descriptor() ([]byte, []int) {
	return fileDescriptor_43fb9bc5eb13a2f0, []int{5}
}

func (m *Identification) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Identification.Unmarshal(m, b)
}
func (m *Identification) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Identification.Marshal(b, m, deterministic)
}
func (m *Identification) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Identification.Merge(m, src)
}
func (m *Identification) XXX_Size() int {
	return xxx_messageInfo_Identification.Size(m)
}
func (m *Identification) XXX_DiscardUnknown() {
	xxx_messageInfo_Identification.DiscardUnknown(m)
}

var xxx_messageInfo_Identification proto.InternalMessageInfo

func (m *Identification) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Identification) GetIdType() string {
	if m != nil {
		return m.IdType
	}
	return ""
}

func init() {
	proto.RegisterEnum("interaction.InteractionStatusCode", InteractionStatusCode_name, InteractionStatusCode_value)
	proto.RegisterType((*InteractionStatus)(nil), "interaction.InteractionStatus")
	proto.RegisterType((*InteractionMessage)(nil), "interaction.InteractionMessage")
	proto.RegisterType((*Frame)(nil), "interaction.Frame")
	proto.RegisterType((*ConversationMember)(nil), "interaction.ConversationMember")
	proto.RegisterType((*Role)(nil), "interaction.Role")
	proto.RegisterType((*Identification)(nil), "interaction.Identification")
}

func init() { proto.RegisterFile("interaction.proto", fileDescriptor_43fb9bc5eb13a2f0) }

var fileDescriptor_43fb9bc5eb13a2f0 = []byte{
	// 448 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0xdd, 0x6e, 0xd3, 0x30,
	0x14, 0x5e, 0xba, 0x34, 0xa5, 0x27, 0x10, 0xb5, 0x07, 0x31, 0x45, 0x03, 0xb1, 0x2a, 0x12, 0xa8,
	0xda, 0xc5, 0x84, 0x8a, 0x04, 0x08, 0xae, 0xa0, 0x6c, 0x52, 0x54, 0xe8, 0x90, 0x07, 0xe2, 0x82,
	0xab, 0x2c, 0x3e, 0x9b, 0x2c, 0x25, 0x76, 0xb1, 0xcd, 0xa4, 0xde, 0xf1, 0x22, 0xbc, 0x0f, 0x0f,
	0xc4, 0x03, 0xa0, 0x3a, 0x19, 0x4d, 0xd6, 0x82, 0xb8, 0xf3, 0xf9, 0xbe, 0xef, 0x7c, 0xb6, 0xcf,
	0x0f, 0x0c, 0x85, 0xb4, 0xa4, 0xb3, 0xdc, 0x0a, 0x25, 0x8f, 0x16, 0x5a, 0x59, 0x85, 0x61, 0x03,
	0x4a, 0x66, 0x30, 0x4c, 0xd7, 0xe1, 0x99, 0xcd, 0xec, 0x37, 0x83, 0xcf, 0xc0, 0xcf, 0x15, 0xa7,
	0xd8, 0x1b, 0x79, 0xe3, 0x68, 0x92, 0x1c, 0x35, 0x3d, 0x36, 0xd4, 0x53, 0xc5, 0x89, 0x39, 0x7d,
	0xb2, 0x00, 0x6c, 0xd0, 0xef, 0xc9, 0x98, 0xec, 0x92, 0x70, 0x0c, 0xdd, 0x0b, 0x9d, 0x95, 0x95,
	0x5d, 0x38, 0xc1, 0x96, 0xdd, 0xc9, 0x8a, 0x61, 0x95, 0x00, 0x9f, 0xc0, 0xdd, 0x06, 0x77, 0x5c,
	0x50, 0x49, 0xd2, 0x9a, 0xb8, 0x33, 0xf2, 0xc6, 0xb7, 0xd9, 0x36, 0x2a, 0xf9, 0xd1, 0x81, 0xae,
	0xb3, 0xc0, 0x43, 0x18, 0x18, 0x2a, 0x33, 0x69, 0x45, 0xfe, 0x61, 0xf5, 0xcd, 0x5c, 0x15, 0xee,
	0xc2, 0x3e, 0xdb, 0xc0, 0x11, 0xc1, 0xb7, 0xcb, 0x05, 0x39, 0xe3, 0x3e, 0x73, 0x67, 0x7c, 0x00,
	0xfd, 0xb2, 0x7a, 0x70, 0xca, 0xe3, 0x5d, 0x47, 0xac, 0x01, 0x8c, 0xa1, 0xa7, 0x69, 0x51, 0x2c,
	0xdf, 0x2c, 0x63, 0x7f, 0xe4, 0x8d, 0xef, 0xb0, 0xeb, 0x10, 0x5f, 0xc1, 0x2d, 0x4d, 0x39, 0x89,
	0x2b, 0xd2, 0x71, 0xd7, 0x7d, 0xf0, 0xa0, 0xf5, 0xc1, 0xa9, 0x92, 0x57, 0xa4, 0x4d, 0x56, 0x55,
	0xa4, 0x3c, 0x27, 0xcd, 0xfe, 0x24, 0xe0, 0x73, 0x08, 0x0c, 0x49, 0x4e, 0x3a, 0x0e, 0xfe, 0x2f,
	0xb5, 0x96, 0xe3, 0x63, 0x88, 0xf2, 0x06, 0x9b, 0xf2, 0xb8, 0xe7, 0x9e, 0x7c, 0x03, 0x4d, 0xbe,
	0x7b, 0x80, 0x9b, 0x36, 0x38, 0x85, 0x48, 0x70, 0x92, 0x56, 0x5c, 0x88, 0xdc, 0xe1, 0x75, 0x6f,
	0xee, 0xb7, 0x5b, 0xdd, 0x92, 0xb0, 0x1b, 0x29, 0xf8, 0x08, 0x7c, 0xad, 0x8a, 0xaa, 0x8a, 0xe1,
	0x64, 0xd8, 0x4a, 0x65, 0xaa, 0x20, 0xe6, 0xe8, 0x64, 0x1f, 0xfc, 0x55, 0xb4, 0x2a, 0xba, 0xbc,
	0x9e, 0x82, 0x3e, 0x73, 0xe7, 0xe4, 0x05, 0x44, 0xed, 0x4b, 0x30, 0x82, 0x8e, 0xe0, 0xb5, 0xa6,
	0x23, 0x38, 0xee, 0x41, 0x20, 0xf8, 0xc7, 0x75, 0xb3, 0xea, 0xe8, 0xf0, 0x25, 0xdc, 0xdb, 0x3a,
	0x89, 0x18, 0x42, 0xef, 0xd3, 0x7c, 0x36, 0x3f, 0xfd, 0x3c, 0x1f, 0xec, 0x60, 0x0f, 0x3a, 0xa7,
	0xb3, 0xc1, 0x4f, 0x0f, 0x43, 0x08, 0x4e, 0x5e, 0xa7, 0xef, 0x8e, 0xdf, 0x0e, 0x7e, 0xed, 0x4e,
	0xbe, 0xb6, 0xc6, 0x34, 0x95, 0x97, 0x9a, 0x8c, 0xc1, 0x2f, 0xb0, 0x77, 0x46, 0x92, 0x6f, 0x19,
	0xe0, 0x83, 0xbf, 0x2d, 0x40, 0x2d, 0xd8, 0x7f, 0xf8, 0xef, 0x0d, 0x49, 0x76, 0xce, 0x03, 0xb7,
	0x7a, 0x4f, 0x7f, 0x07, 0x00, 0x00, 0xff, 0xff, 0x61, 0x2d, 0xf3, 0x9a, 0x8f, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// InteractionIngressClient is the client API for InteractionIngress service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type InteractionIngressClient interface {
	SendInteractionMessage(ctx context.Context, in *InteractionMessage, opts ...grpc.CallOption) (*InteractionStatus, error)
}

type interactionIngressClient struct {
	cc grpc.ClientConnInterface
}

func NewInteractionIngressClient(cc grpc.ClientConnInterface) InteractionIngressClient {
	return &interactionIngressClient{cc}
}

func (c *interactionIngressClient) SendInteractionMessage(ctx context.Context, in *InteractionMessage, opts ...grpc.CallOption) (*InteractionStatus, error) {
	out := new(InteractionStatus)
	err := c.cc.Invoke(ctx, "/interaction.InteractionIngress/SendInteractionMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InteractionIngressServer is the server API for InteractionIngress service.
type InteractionIngressServer interface {
	SendInteractionMessage(context.Context, *InteractionMessage) (*InteractionStatus, error)
}

// UnimplementedInteractionIngressServer can be embedded to have forward compatible implementations.
type UnimplementedInteractionIngressServer struct {
}

func (*UnimplementedInteractionIngressServer) SendInteractionMessage(ctx context.Context, req *InteractionMessage) (*InteractionStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendInteractionMessage not implemented")
}

func RegisterInteractionIngressServer(s *grpc.Server, srv InteractionIngressServer) {
	s.RegisterService(&_InteractionIngress_serviceDesc, srv)
}

func _InteractionIngress_SendInteractionMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InteractionMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InteractionIngressServer).SendInteractionMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/interaction.InteractionIngress/SendInteractionMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InteractionIngressServer).SendInteractionMessage(ctx, req.(*InteractionMessage))
	}
	return interceptor(ctx, in, info, handler)
}

var _InteractionIngress_serviceDesc = grpc.ServiceDesc{
	ServiceName: "interaction.InteractionIngress",
	HandlerType: (*InteractionIngressServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendInteractionMessage",
			Handler:    _InteractionIngress_SendInteractionMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "interaction.proto",
}
