#!/bin/bash

echo "Executing script to prepare a clean registry database."

#read -p "Enter path to SQL dumps (generated by emob-backup-user, without trailing slash): " path_to_sql_dumps
#path_to_sql_dumps=$1

echo "host: $POSTGRES_HOST"
echo "port: $POSTGRES_PORT"
echo "db: $POSTGRES_DB"
echo "user: $POSTGRES_USER"
#echo "pw: $POSTGRES_PASSWORD"

#echo "Prepare .pgpass"

#sed -i "s/PW-PLACEHOLDER/${POSTGRES_PASSWORD}/g" .pgpass
#PGPASSFILE="~/registry/.pgpass"

echo "Dropping existing database tables..."

PGPASSWORD=$POSTGRES_PASSWORD dropdb -h $POSTGRES_HOST -p $POSTGRES_PORT -U $POSTGRES_USER -w -e $POSTGRES_DB

echo "Create database new..."

#PGPASSWORD=$POSTGRES_PASSWORD psql -h $POSTGRES_HOST -p $POSTGRES_PORT -U $POSTGRES_USER -d $POSTGRES_DB create_database.sql
PGPASSWORD=$POSTGRES_PASSWORD createdb -h $POSTGRES_HOST -p $POSTGRES_PORT -U $POSTGRES_USER -w -e --tablespace=pg_default --encoding='UTF8' --lc-collate='en_US.utf8' --lc-ctype='en_US.utf8' $POSTGRES_DB

echo "Create tables"

PGPASSWORD=$POSTGRES_PASSWORD psql -h $POSTGRES_HOST -p $POSTGRES_PORT -U $POSTGRES_USER -d $POSTGRES_DB -w -e -f sql/create_assets.sql
PGPASSWORD=$POSTGRES_PASSWORD psql -h $POSTGRES_HOST -p $POSTGRES_PORT -U $POSTGRES_USER -d $POSTGRES_DB -w -e -f sql/create_asset_administration_shells.sql
PGPASSWORD=$POSTGRES_PASSWORD psql -h $POSTGRES_HOST -p $POSTGRES_PORT -U $POSTGRES_USER -d $POSTGRES_DB -w -e -f sql/create_endpoints.sql
PGPASSWORD=$POSTGRES_PASSWORD psql -h $POSTGRES_HOST -p $POSTGRES_PORT -U $POSTGRES_USER -d $POSTGRES_DB -w -e -f sql/create_semantic_protocols.sql
PGPASSWORD=$POSTGRES_PASSWORD psql -h $POSTGRES_HOST -p $POSTGRES_PORT -U $POSTGRES_USER -d $POSTGRES_DB -w -e -f sql/create_roles.sql
PGPASSWORD=$POSTGRES_PASSWORD psql -h $POSTGRES_HOST -p $POSTGRES_PORT -U $POSTGRES_USER -d $POSTGRES_DB -w -e -f sql/create_aas_role.sql
