---
apiVersion: v1
kind: Service
metadata:
  name: https-endpoint-egress
  labels: 
    app: i40-aas
    service: https-endpoint-egress
spec:
  ports:
    - targetPort: endpoint
      port: 80
      protocol: TCP
  selector:
    app: i40-aas
    service: https-endpoint-egress
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: https-endpoint-egress
  labels: 
    app: i40-aas
    service: https-endpoint-egress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: i40-aas
      service: https-endpoint-egress
  template: 
    metadata:
      labels:
        app: i40-aas
        service: https-endpoint-egress
    spec:
      containers:
        - name: service
          image: sapi40/i40-aas-https-endpoint-egress
          ports:
            - name: endpoint
              containerPort: 3000
          resources:
            limits:
              cpu: 50m
              memory: 320M
            requests:
              cpu: 25m
              memory: 273M
          env:
            - name: REGISTRY_URL
              valueFrom: 
                configMapRefKey:
                  name: service-addresses
                  key: REGISTRY_URL
            - name: DATA_MANAGER_URL
              valueFrom: 
                configMapRefKey:
                  name: service-addresses
                  key: DATA_MANAGER_URL
          envFrom:
            - secretRef:
                name: endpoint-registry
            - configMapRef:
                name: endpoint-registry-postgres
            - configMapRef:
                name: rabbitmq
            - secretRef:
                name: rabbitmq
---
