---
apiVersion: v1
kind: Service
metadata:
  name: storage-adapter-mongodb
  labels: 
    app: i40-aas
    service: storage-adapter-mongodb
spec:
  ports:
  - targetPort: endpoint
    port: 80
    protocol: TCP
  selector:
    app: i40-aas
    service: storage-adapter-mongodb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage-adapter-mongodb
  labels: 
    app: i40-aas
    service: storage-adapter-mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: i40-aas
      service: storage-adapter-mongodb
  template: 
    metadata:
      labels:
        app: i40-aas
        service: storage-adapter-mongodb
    spec:
      containers:
        - name: service
          image: sapi40/i40-aas-storage-adapter-mongodb
          ports:
          - name: endpoint
            containerPort: 3100
          resources:
            limits:
              cpu: 50m
              memory: 300M
            requests:
              cpu: 25m
              memory: 263M
          env:
          - name: REGISTRY_URL
            valueFrom: 
              configMapKeyRef:
                name: service-addresses
                key: REGISTRY_URL
          - name: DATA_MANAGER_URL
            valueFrom: 
              configMapKeyRef:
                name: service-addresses
                key: DATA_MANAGER_URL
          envFrom:
            - secretRef:
                name: mongodb-secret
            - configMapRef:
                name: mongodb
            - configMapRef:
                name: rabbitmq
            - secretRef:
                name: rabbitmq
---
