---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq
  labels:
    app: i40-aas
    service: message-broker
data:
  RABBITMQ_AMQP_HOST: rabbitmq-0.rabbitmq-headless-svc
  RABBITMQ_AMQP_PORT: "80"
  RABBITMQ_MQTT_PORT: "1883"
  RABBITMQ_BROKER_TOPIC_EGRESS: http.client
  RABBITMQ_BROKER_EXCHANGE: amq.topic
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq
  labels:
    app: i40-aas
    service: message-broker
type: Opaque
stringData:
  RABBITMQ_BROKER_USER: guest
  RABBITMQ_BROKER_PASSWORD: guest
  RABBITMQ_INGRESS_ADMIN_USER: admin
  RABBITMQ_INGRESS_ADMIN_PASSWORD: admin
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-plugins
  labels:
    app: i40-aas
    service: message-broker
data:
  enabled_plugins: |
    [rabbitmq_management,rabbitmq_mqtt].
---
kind: Service
apiVersion: v1
metadata:
  name: rabbitmq-headless-svc
  labels:
    app: i40-aas
    service: message-broker
spec:
  clusterIP: None
  selector:
    app: i40-aas
    service: message-broker
  ports:
  - name: amqp
    protocol: TCP
    port: 80
    targetPort: 5672
  - name: mqtt
    protocol: TCP
    port: 1883
    targetPort: 1883
---
kind: Service
apiVersion: v1
metadata:
  name: rabbitmq-ui-svc
  labels:
    app: i40-aas
    service: message-broker
spec:
  type: LoadBalancer
  selector:
    app: i40-aas
    service: message-broker
  ports:
  - protocol: TCP
    port: 80
    targetPort: ui
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
  labels:
    app: i40-aas
    service: message-broker
spec:
  serviceName: rabbitmq-headless-svc
  replicas: 1
  selector:
    matchLabels:
      app: i40-aas
      service: message-broker
  template:
    metadata:
      labels:
        app: i40-aas
        service: message-broker
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3-management
        imagePullPolicy: "IfNotPresent"
        env:
        - name: RABBITMQ_DEFAULT_USER
          valueFrom:
            secretKeyRef:
              name: rabbitmq
              key: BROKER_USER
        - name: RABBITMQ_DEFAULT_PASS
          valueFrom:
            secretKeyRef:
              name: rabbitmq
              key: BROKER_PASSWORD
        ports:
        - name: messages
          containerPort: 5672
        - name: ui
          containerPort: 15672
        - name: mqtt
          containerPort: 1883
        volumeMounts:
        - name: rabbitmq-plugins
          mountPath: /etc/rabbitmq/enabled_plugins
          subPath: enabled_plugins
      volumes:
      - name: rabbitmq-plugins
        configMap:
          name: rabbitmq-plugins
---
