---
apiVersion: v1
kind: ConfigMap
metadata:
  name: https-endpoint-ingress
  labels: 
    app: i40-aas
    service: https-endpoint-ingress
data:
  # Networking
  HTTPS_ENDPOINT_INGRESS_PROTOCOL: http
  HTTPS_ENDPOINT_INGRESS_HOST: https-endpoint-ingress
  HTTPS_ENDPOINT_INGRESS_PORT: "80"
---
apiVersion: v1
kind: Secret
metadata:
  name: https-endpoint-ingress
  labels: 
    app: i40-aas
    service: https-endpoint-ingress
type: Opaque
stringData:
  HTTPS_ENDPOINT_INGRESS_USER: admin
  HTTPS_ENDPOINT_INGRESS_PASSWORD: admin
---
apiVersion: v1
kind: Service
metadata:
  name: https-endpoint-ingress
  labels: 
    app: i40-aas
    service: https-endpoint-ingress
spec:
  type: LoadBalancer
  ports:
    - targetPort: endpoint
      port: 80
      protocol: TCP
  selector:
    app: i40-aas
    service: https-endpoint-ingress
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: https-endpoint-ingress
  labels: 
    app: i40-aas
    service: https-endpoint-ingress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: i40-aas
      service: https-endpoint-ingress
  template: 
    metadata:
      labels:
        app: i40-aas
        service: https-endpoint-ingress
    spec:
      containers:
        - name: service
          image: sapi40/i40-aas-https-endpoint-ingress
          ports:
            - name: endpoint
              containerPort: 2000
          resources:
            limits:
              cpu: 83m
              memory: 320M
            requests:
              cpu: 62m
              memory: 273M
          envFrom:
          - configMapRef:
              name: https-endpoint-ingress
          - secretRef:
              name: https-endpoint-ingress
          - configMapRef:
              name: rabbitmq
          - secretRef:
              name: rabbitmq
---
